---
- name: install haproxy
  yum:
    name: haproxy
    state: installed

- name: push file - haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify:
    - 'restart haproxy'

- name: start haproxy
  service:
    name: haproxy
    state: started
    enabled: yes




