---
- name: creating datanode directory
  file: 
    path: '{{item}}'
    owner: '{{hadoop_user}}'
    group: '{{hadoop_group}}'
    state: directory
  with_items: hadoop_hdfs.dfs_dir_datanode

- name: creating yarn local directory
  file:
    path: '{{item}}'
    owner: '{{hadoop_user}}'
    group: '{{hadoop_group}}'
    state: directory
  with_items: hadoop_yarn.yarn_nodemgr_local_dir

- name: start datanode
  command: "/bin/bash {{common['soft_link_base_path']}}/hadoop/sbin/hadoop-daemon.sh start datanode"
  sudo: yes
  sudo_user: "{{hadoop_user}}"

- name: starte nodemanager
  command: "/bin/bash {{common['soft_link_base_path']}}/hadoop/sbin/yarn-daemon start nodemanager"
  sudo: yes
  sudo_user: "{{hadoop_user}}"



