---
- hosts: all
  gather_facts: False
  vars:
    list: [1,2,3,4]
    one: 1
    two: 'second'
  tasks:
    - name: run command
      shell: df -h
      register: info

    - name: debug pprint filter
      debug:
        msg: "{{ info.stdout | pprint }}"

    - name: debug conditionals filter
      debug:
        msg: "The run commands status is changed"
      #when: info|changed
      when: info is changed

    - name: debug int capitalize filter
      debug: 
        msg: "The int value {{ one | int }} The lower value is {{ two | capitalize }}"

    - name: debug default filter
      debug:
        msg: "The variable value is {{ ansible | default('ansible is not define') }}"

    - name: debug list max and min filter
      debug:
        msg: "The list max value is {{ list | max }} The list min value is {{ list | min }}"

    - name:
      debug:
        msg: "The list random value is {{ list | random }} and generate a random value is {{ 1000|random(1,10) }}"

    - name: debug join filter
      debug:
        msg: "The join filter value is {{ list|join('+') }}"

    - name: debug replace and regex_replace filter
      debug:
        msg: "The replace value is {{ two | replace('s','S') }}
                The regex_replace value is {{ two | regex_replace('(.*)ond$','\\1curity') }}"
      

