---
- hosts: all
  gather_facts: False
  tasks:
    - name: register variable
      command: hostname
      register: info

    - name: display variable
      debug: msg="The Variable is {{ info['stdout'] }}"
