---
- name: install zabbix-agent
  yum:
    name: zabbix-agent
    state: installed


- name: push zabbix-agent configfile
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify:
    - 'restart zabbix-agent'

- name: start zabbix-agent
  service:
    name: zabbix-agent
    state: started

 

