---
- hosts: all
  tasks:
  - name: set enforce 0
    command: setenforce 0
  - name: install epel-release repository
    yum:
      name: epel-release
      state: installed
      update_cache: yes
  - name: Set timezone to Asia/Shanghai
    timezone:
      name: Asia/Shanghai
      hwclock:
        UTC

- hosts: web
  vars:
    http_port: 8080
  remote_user: root
  tasks:
  - name: ensure apache is at the present version
    yum:
      name: httpd
      state: present
  - name: write the apache config file
    template:
      src: conf/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart apache
  handlers:
  - name: restart apache
    service:
      name: httpd
      state: restarted

- hosts: node3
  remote_user: root
  tasks:
  - name: ensure postgresql is at present version
    yum:
      name: 
        - postgresql-server
        - postgresql
      state: present
    notify: initialize pgsql
  - name: ensure the postgresql is started
    service:
      name: postgresql
      state: started
  handlers:
  - name: initialize pgsql
    command: /usr/bin/postgresql-setup initdb
    become: yes
    become_user: postgres
