---
- hosts: node2
  vars:
    http_port: 8080
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: write the apache config file1
    template:
      src:  /root/ansible_playbooks/apache/conf/00-mpm.conf.j2
      dest: /etc/httpd/conf.modules.d/00-mpm.conf
    notify:
    - restart apache
  - name: write the apache config file2
    template:
      src: /root/ansible_playbooks/apache/conf/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
      
  handlers:
  - name: restart apache
    service: 
      name: httpd
      state: restarted
