---
- hosts: node2
  remote_user: root
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped
      enabled: no
  - name: uninstall httpd
    yum:
      name: httpd
      state: absent
